services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=backend-crud
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data:
